### ISSUE TITLE
eslint run by IDEs doesn't see any configuration from ace

### ISSUE THREAD

**Issue by rymach** [connexta/ace#14]
`catalog-ui-search/.eslintrc.js` was recently added in DDF and some IDEs are picking up this file and using it to lint code in the editor window. unfortunately, eslint defaults to es5 b/c it doesn't know about the configuration in ace () when it is called from the IDE

reported by @Bdthomson

**Comment by rymach** [comment]
suggest removing eslint configuration from ace (and adding it to downstream projects)

**Comment by djblue** [comment]
We should make the esline rules available for downstream projects the same way we do for [prettierrc.js](https://github.com/connexta/ace/blob/master/prettierrc.js).

**Comment by rymach** [comment]
I think if we drop an .eslintrc.js file into the ace repo IDEs/eslint still wont see it automatically
